version: 2.1
jobs:
  build:
    docker:
      - image: circleci/golang:latest
      - image: circleci/mysql:5.7-ram
    environment:
      GO111MODULE: "on"
      FAKE_DB_HOST: "127.0.0.1:3306"
      FAKE_DB_PASSWORD: "null"
    working_directory: /go/src/github.com/miyauchi-sup/codecov_test
    steps:
      - checkout
      - run: sudo apt install -y default-mysql-client
      - run: GO111MODULE=off go get golang.org/x/lint/golint
      - run: go vet -v $(go list ./... |grep -v 'vendor')
      - run: golint $(go list ./... |grep -v 'vendor')
      - run: go get -v github.com/rubenv/sql-migrate/...
      - run: mysql -h 127.0.0.1 -u root -e "CREATE DATABASE IF NOT EXISTS pocket_test DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_bin"
      - run: sql-migrate up -env="circleci"
      - run: mysql -h 127.0.0.1 -u root pocket_test < seeds/seed.sql
      - run: go test -cover $(go list ./... |grep -v 'vendor')
      - setup_remote_docker:
          docker_layer_caching: true
      - run: make docker/api/build
